DROP TABLE IF EXISTS ISSUES;

CREATE TABLE ISSUES (
    ISSUE_NUMBER BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUTHOR_ID BIGINT,
    TITLE VARCHAR(255),
    STATUS VARCHAR(50),
    CREATED_AT DATETIME,
    MILESTONE_ID BIGINT
);

DROP TABLE IF EXISTS COMMENTS;

CREATE TABLE COMMENTS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    CONTENT TEXT,
    TYPE VARCHAR(16) NOT NULL,
    ATTACHMENT_KEY VARCHAR(),
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME,
    USER_ID BIGINT,
    ISSUE_NUMBER BIGINT,
    CONSTRAINT FK_ISSUE_NUMBER FOREIGN KEY (ISSUE_NUMBER) REFERENCES ISSUES(ISSUE_NUMBER)
)