DROP TABLE IF EXISTS issues;
DROP TABLE IF EXISTS labels;

CREATE TABLE ISSUES (
    ISSUE_NUMBER BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUTHOR_ID BIGINT,
    TITLE VARCHAR(255),
    STATUS VARCHAR(50),
    CREATED_AT DATETIME,
    MILESTONE_ID BIGINT
);
CREATE TABLE LABELS (
    LABEL_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(100),
    BACKGROUND_COLOR CHAR(7) NOT NULL,
    TEXT_COLOR VARCHAR(7) NOT NULL
);
CREATE TABLE ISSUE_LABELS
(
    ISSUE_NUMBER BIGINT,
    LABEL_ID     BIGINT,
    PRIMARY KEY (ISSUE_NUMBER, LABEL_ID)
    INDEX idx_label_id (LABEL_ID)
);
