DROP TABLE IF EXISTS issues;

CREATE TABLE ISSUES (
    ISSUE_NUMBER BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUTHOR_ID BIGINT,
    TITLE VARCHAR(255),
    STATUS VARCHAR(50),
    CREATED_AT DATETIME,
    MILESTONE_ID BIGINT
);